platform :ios, '8.0'
use_frameworks!

def pods
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'MJRefresh', '~> 3.1.9'
    pod 'pop', '~> 1.0'
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'TPKeyboardAvoiding', '~> 1.3'
    pod 'YYModel', '~> 1.0.4'
    pod 'HMSegmentedControl', '~> 1.5.2'
end

target 'ZhaoChe' do
    pods
end

